import {
  AnyComponentConfig,
  ComponentCategory,
  ComponentType,
} from './types';

export interface ComponentMetadata {
  type: ComponentType;
  name: string;
  category: ComponentCategory;
  description: string;
  iconName: string;
  defaultConfig: (id: string, customName?: string) => AnyComponentConfig;
}

export const COMPONENT_METADATA_LIST: ComponentMetadata[] = [
  // Compute
  {
    type: 'client',
    name: 'Client',
    category: 'compute',
    description: 'Browser or mobile client generating inbound traffic',
    iconName: 'Smartphone',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Client',
      type: 'client',
      category: 'compute',
      health: 'healthy',
      requestRateQps: 100,
      connectionType: 'HTTP/2',
      requestPayloadKb: 2,
      operationType: 'mixed',
      readPercentage: 80,
      requestKeyDistribution: 'uniform',
      requestKeySpaceSize: 100,
      maxThroughputQps: 10000,
    }),
  },
  {
    type: 'app_server',
    name: 'App Server',
    category: 'compute',
    description: 'Stateless backend application server handling business logic',
    iconName: 'Server',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'App Server',
      type: 'app_server',
      category: 'compute',
      health: 'healthy',
      replicas: 2,
      maxConnections: 1000,
      processingLatencyMs: 15,
      failureRatePercent: 0,
      maxThroughputQps: 2000,
    }),
  },
  {
    type: 'worker',
    name: 'Background Worker',
    category: 'compute',
    description: 'Async worker consuming tasks or messages',
    iconName: 'Cpu',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Worker',
      type: 'worker',
      category: 'compute',
      health: 'healthy',
      replicas: 2,
      jobProcessingRatePerSec: 50,
      retryLimit: 3,
      concurrencyLimit: 20,
      processingLatencyMs: 20,
      maxThroughputQps: 500,
    }),
  },
  {
    type: 'serverless',
    name: 'Serverless Function',
    category: 'compute',
    description: 'Event-driven on-demand compute function',
    iconName: 'Zap',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Serverless Func',
      type: 'serverless',
      category: 'compute',
      health: 'healthy',
      coldStartLatencyMs: 150,
      concurrencyLimit: 1000,
      timeoutMs: 10000,
      memoryMb: 512,
      baseExecutionLatencyMs: 25,
      warmInstances: 0,
      idleTimeoutSec: 300,
      maxThroughputQps: 3000,
    }),
  },

  // Networking
  {
    type: 'load_balancer',
    name: 'Load Balancer',
    category: 'networking',
    description: 'Distributes incoming traffic across backend instances',
    iconName: 'GitFork',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Load Balancer',
      type: 'load_balancer',
      category: 'networking',
      health: 'healthy',
      algorithm: 'round_robin',
      healthCheckIntervalSec: 5,
      healthRecoveryDelaySec: 10,
      stickySession: false,
      targetWeights: {},
      maxThroughputQps: 50000,
    }),
  },
  {
    type: 'api_gateway',
    name: 'API Gateway',
    category: 'networking',
    description: 'Entry point for routing, authentication, and throttling',
    iconName: 'DoorOpen',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'API Gateway',
      type: 'api_gateway',
      category: 'networking',
      health: 'healthy',
      rateLimitQps: 5000,
      authMode: 'JWT',
      timeoutMs: 5000,
      circuitBreakerEnabled: true,
      maxThroughputQps: 20000,
    }),
  },
  {
    type: 'cdn',
    name: 'CDN',
    category: 'networking',
    description: 'Content delivery network for static assets and edge caching',
    iconName: 'Globe',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'CDN Edge',
      type: 'cdn',
      category: 'networking',
      health: 'healthy',
      cacheTtlSec: 86400,
      edgeLocationsCount: 50,
      originShielding: true,
      hitRatioPercent: 85,
      maxThroughputQps: 100000,
    }),
  },
  {
    type: 'dns',
    name: 'DNS Resolver',
    category: 'networking',
    description: 'Domain name resolution and geographic routing',
    iconName: 'Network',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'DNS',
      type: 'dns',
      category: 'networking',
      health: 'healthy',
      ttlSec: 300,
      lookupLatencyMs: 20,
      routingPolicy: 'latency_based',
      targetWeights: {},
      maxThroughputQps: 500000,
    }),
  },
  {
    type: 'firewall',
    name: 'Firewall / WAF',
    category: 'networking',
    description: 'Web application firewall filtering malicious requests',
    iconName: 'Shield',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'WAF Firewall',
      type: 'firewall',
      category: 'networking',
      health: 'healthy',
      ruleCount: 25,
      inspectionLatencyMs: 2,
      blockRatePercent: 1,
      maxThroughputQps: 25000,
    }),
  },
  {
    type: 'reverse_proxy',
    name: 'Reverse Proxy',
    category: 'networking',
    description: 'Handles SSL termination, compression, and request buffering',
    iconName: 'ArrowLeftRight',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Reverse Proxy',
      type: 'reverse_proxy',
      category: 'networking',
      health: 'healthy',
      enableCompression: true,
      cacheRules: 'static/*; gzip',
      maxConnections: 10000,
      bufferingEnabled: true,
      bufferSizeKb: 1024,
      upstreamBandwidthMbps: 100,
      maxThroughputQps: 30000,
    }),
  },

  // Storage
  {
    type: 'sql_db',
    name: 'SQL Database',
    category: 'storage',
    description: 'Relational ACID database with primary and replica support',
    iconName: 'Database',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'PostgreSQL DB',
      type: 'sql_db',
      category: 'storage',
      health: 'healthy',
      replicas: 1,
      readReplicasCount: 2,
      baseLatencyMs: 20,
      maxConnections: 500,
      connectionQueueLimit: 500,
      shardCount: 1,
      isolationLevel: 'Read Committed',
      replicationLagMs: 50,
      automaticFailover: true,
      failoverLatencyMs: 300,
      maxThroughputQps: 2500,
    }),
  },
  {
    type: 'nosql_db',
    name: 'NoSQL Database',
    category: 'storage',
    description: 'Horizontally scalable key-document or wide-column store',
    iconName: 'Boxes',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'NoSQL Store',
      type: 'nosql_db',
      category: 'storage',
      health: 'healthy',
      partitionKey: 'user_id',
      consistencyLevel: 'eventual',
      replicas: 3,
      partitionCount: 16,
      baseLatencyMs: 8,
      replicationLagMs: 15,
      maxThroughputQps: 15000,
    }),
  },
  {
    type: 'object_storage',
    name: 'Object Storage (S3)',
    category: 'storage',
    description: 'Blob storage for media, files, and large immutable objects',
    iconName: 'HardDrive',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Object Storage',
      type: 'object_storage',
      category: 'storage',
      health: 'healthy',
      latencyMs: 35,
      throughputMbPerSec: 200,
      storageClass: 'Standard',
      maxThroughputQps: 5000,
    }),
  },
  {
    type: 'search_index',
    name: 'Search Index',
    category: 'storage',
    description: 'Distributed inverted index for full-text search',
    iconName: 'Search',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Search Index',
      type: 'search_index',
      category: 'storage',
      health: 'healthy',
      shards: 5,
      replicas: 2,
      indexingLatencyMs: 50,
      queryLatencyMs: 12,
      maxThroughputQps: 4000,
    }),
  },
  {
    type: 'graph_db',
    name: 'Graph Database',
    category: 'storage',
    description: 'Optimized node-and-edge storage for social graphs',
    iconName: 'Share2',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Graph DB',
      type: 'graph_db',
      category: 'storage',
      health: 'healthy',
      queryLatencyMs: 30,
      traversalDepthLimit: 3,
      traversalDepth: 2,
      maxThroughputQps: 1500,
    }),
  },
  {
    type: 'timeseries_db',
    name: 'Time-Series DB',
    category: 'storage',
    description: 'Appends metrics, telemetry, and time-ordered data points',
    iconName: 'Activity',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Time-Series DB',
      type: 'timeseries_db',
      category: 'storage',
      health: 'healthy',
      writeThroughputPerSec: 50000,
      retentionDays: 90,
      queryLatencyMs: 15,
      maxThroughputQps: 30000,
    }),
  },

  // Caching
  {
    type: 'redis_cache',
    name: 'In-Memory Cache (Redis)',
    category: 'caching',
    description: 'Fast sub-millisecond key-value cache and data structure store',
    iconName: 'Layers',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Redis Cluster',
      type: 'redis_cache',
      category: 'caching',
      health: 'healthy',
      sizeMb: 16384,
      evictionPolicy: 'LRU',
      hitRatioPercent: 80,
      replicas: 2,
      readLatencyMs: 2,
      ttlSec: 300,
      entrySizeKb: 1,
      requestCoalescingEnabled: false,
      maxThroughputQps: 100000,
    }),
  },
  {
    type: 'local_cache',
    name: 'Local Server Cache',
    category: 'caching',
    description: 'Process-level in-memory cache on app servers',
    iconName: 'Disc',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Local Cache',
      type: 'local_cache',
      category: 'caching',
      health: 'healthy',
      sizeMb: 512,
      ttlSec: 60,
      hitRatioPercent: 50,
      evictionPolicy: 'LRU',
      readLatencyMs: 0.5,
      entrySizeKb: 1,
      requestCoalescingEnabled: false,
      maxThroughputQps: 50000,
    }),
  },
  {
    type: 'cdn_cache',
    name: 'CDN Edge Cache',
    category: 'caching',
    description: 'Edge points of presence caching HTTP responses',
    iconName: 'Cloud',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'CDN Cache',
      type: 'cdn_cache',
      category: 'caching',
      health: 'healthy',
      ttlSec: 3600,
      hitRatioPercent: 75,
      readLatencyMs: 8,
      requestCoalescingEnabled: true,
      maxThroughputQps: 200000,
    }),
  },
  {
    type: 'browser_cache',
    name: 'Browser Cache',
    category: 'caching',
    description: 'Client device storage for static assets and API responses',
    iconName: 'Monitor',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Browser Cache',
      type: 'browser_cache',
      category: 'caching',
      health: 'healthy',
      ttlSec: 86400,
      hitRatioPercent: 40,
      readLatencyMs: 0.2,
      requestCoalescingEnabled: true,
      maxThroughputQps: 1000000,
    }),
  },

  // Messaging
  {
    type: 'message_queue',
    name: 'Message Queue (Kafka)',
    category: 'messaging',
    description: 'Distributed partitioned log for high-throughput stream ingestion',
    iconName: 'ListOrdered',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Message Queue',
      type: 'message_queue',
      category: 'messaging',
      health: 'healthy',
      partitions: 8,
      consumerGroups: 2,
      maxDepth: 50000,
      orderingGuarantee: 'Partition Key',
      retentionHours: 72,
      overflowPolicy: 'reject_newest',
      consumerThroughputPerSec: 2000,
      producerAckLatencyMs: 4,
      consumerProcessingLatencyMs: 10,
      deliveryGuarantee: 'at_least_once',
      retryLimit: 3,
      retryDelayMs: 100,
      deadLetterQueue: true,
      maxThroughputQps: 50000,
    }),
  },
  {
    type: 'pubsub',
    name: 'Pub/Sub Broker',
    category: 'messaging',
    description: 'Many-to-many topic based asynchronous event broadcaster',
    iconName: 'Radio',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Pub/Sub',
      type: 'pubsub',
      category: 'messaging',
      health: 'healthy',
      topicCount: 10,
      subscribersPerTopic: 5,
      deliveryGuarantee: 'at_least_once',
      maxDepth: 50000,
      retentionHours: 24,
      overflowPolicy: 'reject_newest',
      consumerThroughputPerSec: 2000,
      producerAckLatencyMs: 3,
      consumerProcessingLatencyMs: 10,
      retryLimit: 3,
      retryDelayMs: 100,
      deadLetterQueue: true,
      orderingGuarantee: 'None',
      maxThroughputQps: 30000,
    }),
  },
  {
    type: 'event_bus',
    name: 'Event Bus',
    category: 'messaging',
    description: 'Central message routing fabric across services',
    iconName: 'Shuffle',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Event Bus',
      type: 'event_bus',
      category: 'messaging',
      health: 'healthy',
      throughputPerSec: 10000,
      fanoutFactor: 3,
      maxDepth: 50000,
      retentionHours: 24,
      overflowPolicy: 'reject_newest',
      producerAckLatencyMs: 2,
      consumerProcessingLatencyMs: 8,
      deliveryGuarantee: 'at_least_once',
      retryLimit: 3,
      retryDelayMs: 100,
      deadLetterQueue: true,
      orderingGuarantee: 'None',
      maxThroughputQps: 20000,
    }),
  },
  {
    type: 'task_queue',
    name: 'Task Queue (RabbitMQ)',
    category: 'messaging',
    description: 'Point-to-point worker queue with priority routing and DLQs',
    iconName: 'CheckSquare',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Task Queue',
      type: 'task_queue',
      category: 'messaging',
      health: 'healthy',
      priorityLevels: 3,
      retryLimit: 5,
      deadLetterQueue: true,
      maxDepth: 10000,
      retentionHours: 24,
      overflowPolicy: 'reject_newest',
      consumerThroughputPerSec: 500,
      producerAckLatencyMs: 4,
      consumerProcessingLatencyMs: 20,
      deliveryGuarantee: 'at_least_once',
      retryDelayMs: 250,
      orderingGuarantee: 'FIFO',
      maxThroughputQps: 10000,
    }),
  },

  // Security
  {
    type: 'rate_limiter',
    name: 'Rate Limiter',
    category: 'security',
    description: 'Enforces request quotas to prevent traffic flooding',
    iconName: 'Gauge',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Rate Limiter',
      type: 'rate_limiter',
      category: 'security',
      health: 'healthy',
      algorithm: 'token_bucket',
      limitQps: 1000,
      windowSizeSec: 1,
      maxThroughputQps: 50000,
    }),
  },
  {
    type: 'auth_service',
    name: 'Auth Service',
    category: 'security',
    description: 'Token issue, session validation, and OAuth2 broker',
    iconName: 'Key',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'Auth Service',
      type: 'auth_service',
      category: 'security',
      health: 'healthy',
      tokenType: 'JWT',
      ttlMinutes: 60,
      validationLatencyMs: 3,
      maxThroughputQps: 15000,
    }),
  },
  {
    type: 'encryption_service',
    name: 'Secrets & KMS',
    category: 'security',
    description: 'Hardware key management, encryption, and decryption engine',
    iconName: 'Lock',
    defaultConfig: (id, name) => ({
      id,
      name: name || 'KMS Vault',
      type: 'encryption_service',
      category: 'security',
      health: 'healthy',
      algorithm: 'AES-256-GCM',
      keyRotationDays: 90,
      overheadLatencyMs: 4,
      maxThroughputQps: 20000,
    }),
  },
];

export const COMPONENT_METADATA_MAP = new Map<ComponentType, ComponentMetadata>(
  COMPONENT_METADATA_LIST.map((meta) => [meta.type, meta])
);

export function getComponentMetadata(type: ComponentType): ComponentMetadata {
  const meta = COMPONENT_METADATA_MAP.get(type);
  if (!meta) {
    throw new Error(`Unknown component type: ${type}`);
  }
  return meta;
}

export function createDefaultConfig(type: ComponentType, id: string, name?: string): AnyComponentConfig {
  const meta = getComponentMetadata(type);
  return meta.defaultConfig(id, name);
}
