import type { CalculatorInputs, OverallMetrics, TrafficConfig } from '../../model/types';

export const createInitialTrafficConfig = (): TrafficConfig => ({
  pattern: 'steady',
  baseQps: 500,
  burstMultiplier: 3,
  rampDurationSec: 30,
  spikeFrequencySec: 10,
  seed: 1,
  requestKeyDistribution: 'uniform',
  requestKeySpaceSize: 100,
});

export const createInitialMetrics = (): OverallMetrics => ({
  totalRequestsSent: 0,
  totalRequestsSuccess: 0,
  totalRequestsFailed: 0,
  currentQps: 0,
  avgEndToEndLatencyMs: 0,
  p50LatencyMs: 0,
  p95LatencyMs: 0,
  p99LatencyMs: 0,
  overallErrorRatePercent: 0,
  overallCacheHitRatioPercent: 0,
  totalCacheHits: 0,
  totalCacheMisses: 0,
  totalCacheBypasses: 0,
  totalCacheCoalescedRequests: 0,
  totalProducerAccepted: 0,
  totalProducerRejected: 0,
  totalConsumerSucceeded: 0,
  totalConsumerFailed: 0,
  totalMessageRetries: 0,
  totalMessagesDropped: 0,
  totalMessagesExpired: 0,
  totalDeadLettered: 0,
  timeSeries: [],
  componentMetrics: {},
});

export const createInitialCalculatorInputs = (): CalculatorInputs => ({
  qps: 10_000,
  payloadSizeKb: 2,
  retentionDays: 365,
  readWriteRatio: 10,
  replicationFactor: 3,
  slaAvailabilityPercent: 99.99,
  serverCapacityQps: 2_000,
  readRequestPayloadKb: 0.5,
  readResponsePayloadKb: 2,
  writeResponsePayloadKb: 0.2,
  dbAverageServiceTimeMs: 20,
  dbTargetUtilizationPercent: 70,
  cacheWorkingSetDays: 1,
  cacheHotSetPercent: 20,
  cacheCompressionRatio: 0.7,
  serverTargetUtilizationPercent: 70,
  serverHeadroomPercent: 20,
  failoverCapacityPercent: 20,
  indexingOverheadPercent: 20,
  metadataOverheadPercent: 5,
  storageCompressionRatio: 0.7,
  annualGrowthPercent: 30,
});
