import { describe, expect, it } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/react';
import App from '../App';

describe('Product contract labels', () => {
  it('labels modeled telemetry, analysis, traces, costs, and calculator results', () => {
    render(<App />);

    expect(screen.getByText('Illustrative')).toBeInTheDocument();

    fireEvent.click(screen.getByTitle('Click to open full Metrics & Telemetry Dashboard (M)'));
    expect(
      screen.getByLabelText(
        "Simulated output: Telemetry is generated by SysSim's synthetic model, not observed production traffic.",
      ),
    ).toBeInTheDocument();

    fireEvent.click(screen.getByRole('button', { name: /Bottleneck Inspector/ }));
    expect(
      screen.getByLabelText(
        'Heuristic guidance: Findings are rules-based design prompts, not proof of production readiness.',
      ),
    ).toBeInTheDocument();

    fireEvent.click(screen.getByRole('button', { name: '5-Pillar Health Radar' }));
    expect(
      screen.getByLabelText(
        'Heuristic guidance: Scores summarize simplified rules and simulated telemetry; they are not an architecture certification.',
      ),
    ).toBeInTheDocument();

    fireEvent.click(screen.getByRole('button', { name: 'Distributed Traces' }));
    expect(
      screen.getByLabelText(
        'Simulated output: Traces are synthetic model paths, not telemetry captured from a deployed system.',
      ),
    ).toBeInTheDocument();

    fireEvent.click(screen.getByRole('button', { name: 'Cloud Cost Estimator' }));
    expect(
      screen.getByLabelText(
        'Planning estimate: Static example rates are illustrative and are not a cloud-provider quote.',
      ),
    ).toBeInTheDocument();

    fireEvent.click(screen.getByRole('button', { name: 'Calculator' }));
    expect(
      screen.getByLabelText(
        'Planning estimate: Results use simplified workload assumptions and are not production capacity guarantees.',
      ),
    ).toBeInTheDocument();
  });
});
